### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by supmyhava** [masbagusyutl/coub#1]
root@od-big:~/coub# python3 coub.py
Total Accounts: 1
Processing Account 1/1
Failed to retrieve user rewards. Status code: 500
Task: Welcome Task, Price: 10, Status: ready-to-claim
Failed to complete task 'Welcome Task' (ID: 1). Status code: 500
Task: Daily Check-in, Price: 5, Status: ready-to-start
Failed to complete task 'Daily Check-in' (ID: 2). Status code: 500
Task: Watch 10 Coub, Price: 20, Status: ready-to-start
Failed to complete task 'Watch 10 Coub' (ID: 3). Status code: 500
Task: Share 3 Coub, Price: 15, Status: ready-to-start

**Comment by masbagusyutl** [comment]
Baca tutor di https://t.me/nyariairdrop/2686

Pada Min, 22 Sep 2024, 18.00, supmyhava ***@***.***> menulis:
